import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/**
 * ReviewQR's durable model. Customer-authored text is deliberately absent:
 * drafts and optional details remain browser/request scoped in the MVP.
 * Timestamps are Unix milliseconds, generated by the application so tests and
 * fixtures can control time deterministically.
 */
export const restaurants = sqliteTable(
  "restaurants",
  {
    id: text("id").primaryKey(),
    publicId: text("public_id").notNull(),
    slug: text("slug").notNull(),
    displayName: text("display_name").notNull(),
    locationLabel: text("location_label").notNull(),
    googleReviewUrl: text("google_review_url").notNull(),
    approvedFactsJson: text("approved_facts_json").notNull().default("[]"),
    status: text("status", { enum: ["active", "inactive"] })
      .notNull()
      .default("inactive"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    uniqueIndex("restaurants_public_id_uq").on(table.publicId),
    uniqueIndex("restaurants_slug_uq").on(table.slug),
    index("restaurants_status_idx").on(table.status),
  ],
);

export const topics = sqliteTable(
  "topics",
  {
    id: text("id").primaryKey(),
    restaurantId: text("restaurant_id")
      .notNull()
      .references(() => restaurants.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    promptDescriptor: text("prompt_descriptor").notNull(),
    sortOrder: integer("sort_order").notNull(),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [
    uniqueIndex("topics_restaurant_label_uq").on(
      table.restaurantId,
      table.label,
    ),
    index("topics_restaurant_order_idx").on(
      table.restaurantId,
      table.active,
      table.sortOrder,
    ),
  ],
);

export const reviewSessions = sqliteTable(
  "review_sessions",
  {
    id: text("id").primaryKey(),
    restaurantId: text("restaurant_id")
      .notNull()
      .references(() => restaurants.id, { onDelete: "cascade" }),
    createdAt: integer("created_at").notNull(),
    lastActivityAt: integer("last_activity_at").notNull(),
  },
  (table) => [index("review_sessions_restaurant_idx").on(table.restaurantId)],
);

export const analyticsEvents = sqliteTable(
  "analytics_events",
  {
    id: text("id").primaryKey(),
    restaurantId: text("restaurant_id")
      .notNull()
      .references(() => restaurants.id, { onDelete: "cascade" }),
    sessionId: text("session_id")
      .notNull()
      .references(() => reviewSessions.id, { onDelete: "cascade" }),
    eventType: text("event_type", {
      enum: [
        "qr_page_viewed",
        "rating_selected",
        "topics_selected",
        "draft_generated",
        "draft_generation_failed",
        "draft_edited",
        "draft_copied",
        "google_handoff_clicked",
        "completion_self_reported",
      ],
    }).notNull(),
    rating: integer("rating"),
    metadataJson: text("metadata_json").notNull().default("{}"),
    dedupeKey: text("dedupe_key"),
    occurredAt: integer("occurred_at").notNull(),
  },
  (table) => [
    uniqueIndex("analytics_events_dedupe_key_uq").on(table.dedupeKey),
    index("analytics_events_restaurant_type_time_idx").on(
      table.restaurantId,
      table.eventType,
      table.occurredAt,
    ),
    index("analytics_events_session_time_idx").on(
      table.sessionId,
      table.occurredAt,
    ),
  ],
);

export const operationKeys = sqliteTable(
  "operation_keys",
  {
    scope: text("scope").notNull(),
    key: text("key").notNull(),
    responseRef: text("response_ref").notNull(),
    createdAt: integer("created_at").notNull(),
    expiresAt: integer("expires_at").notNull(),
  },
  (table) => [
    uniqueIndex("operation_keys_scope_key_uq").on(table.scope, table.key),
    index("operation_keys_expiry_idx").on(table.expiresAt),
  ],
);

export const rateLimitBuckets = sqliteTable(
  "rate_limit_buckets",
  {
    bucketKey: text("bucket_key").primaryKey(),
    count: integer("count").notNull(),
    windowStartedAt: integer("window_started_at").notNull(),
    expiresAt: integer("expires_at").notNull(),
  },
  (table) => [index("rate_limit_buckets_expiry_idx").on(table.expiresAt)],
);
